import type { Metadata } from "next";

import "./globals.css";
import Nav from '@/components/Navigation/Nav';



export const metadata: Metadata = {
  title: "Ticketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
