import type { Metadata } from 'next';

import './globals.css';
import Nav from '@/components/Navigation/Nav';

export const metadata: Metadata = {
  title: 'Ticketing',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
